### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by sizer** [sizer/gorfc#2]
## usecases

- [ ] post a tweet about RFC per 1 day.
  - [ ] fetch RFC
    - [ ] new RFC(not posted)
    - [ ] random
- [ ] update RFC data
  - [ ] fetch new rfc-index.xml
    - [ ] request https://www.rfc-editor.org/rfc-index.xml and cache it.
- [ ] fetch rfc detail page.
  - [x] https://www.rfc-editor.org/rfc/rfc8493.txt
    - fetch.RfcDetail #1
  - [ ] https://www.rfc-editor.org/std/std92.txt
